### ISSUE TITLE
koffi: node-raylib

### ISSUE THREAD

**Issue by konsumer** [Koromix/luigi#1]
Hi, I am working over on [node-raylib](https://github.com/RobLoach/node-raylib/tree/raylib4) and we have been doing some FFI  experiments with different FFI libs, in the hopes of getting something that performs close (or at least close enough) to NAPI, but also doesn't require all the bindings to be written in C. You can see some of the experiments I have [here](https://github.com/konsumer/node-raylib-ffi). Our current path on node-raylib is NAPI wrapper code-generation, and then compiling that, but if we could get similar performance in FFI (with bindings written in js) I think it'd be easier to use.

Have you done any performance comparisons with ffi-napi, (and ref-napi, ref-struct-di, etc)?

**Comment by Koromix** [comment]
Hi,

Our goals kind of align, because using Raylib directly through FFI is the initial motivation behind this FFI library.
I haven't done focused benchmarks yet, but I can already tell you that using Raylib through this performs MUCH better than node-ffi/node-ffi-napi/etc.

I also wanted to make it simple, dependable, so it does eveyrthing by itself, and does not use the ref* modules. Or even libffi, this package has its own assembly for each supported platform.

Over the next two weeks I will work on two things:

- Complete the API (right now it cannot be used for out parameters), then we can move on to 1.0.0
- Finish my qemu-based test suite (so I and everyone can test the package on all supported architectures at once)

Right after that, some simple benchmarks would be good. Given our shared goals, I'm guessing something based on rendering a lot of stuff with Raylib, comparing: native / node-ffi / node-raylib / koffi. But I haven't spent much time  thinking on this yet.

Once repeatable benchmarks are in place, I'll go optimisation mode :) Maximum performance should be the number one goal of FFI.

**Comment by Koromix** [comment]
Just a heads up, the QEMU-bsaed testing system was a bit of a pain to set up, but it's getting pretty reliable now :)

![image](https://user-images.githubusercontent.com/871846/158494370-e1ec3a1f-5dda-40c5-914f-acd6c0c14461.png)

**Comment by Koromix** [comment]
I have added a simple benchmark (in C, with node-ffi, and with Koffi), the results are here: https://github.com/Koromix/luigi/tree/master/koffi#benchmarks

It can certainly be improved though, because the Raylib calls in this version are quite heavy (ImageDrawTextEx). Still, the difference with node-ffi is scary.

**Comment by Koromix** [comment]
Closing this now that benchmarks are in place and Koffi is working pretty well already :)
