### ISSUE TITLE
koffi: x64 ABI / calling convention [Question]

### ISSUE THREAD

**Issue by xan105** [Koromix/luigi#13]
How does koffi handle x64 ABI ?
I noticed recently that ffi-napi exports ffi.FFI_WIN64 and ffi.FFI_UNIX64

Example
```js
const lib = ffi.Library("shell32.dll", {
  SHQueryUserNotificationState: ["long", ["int32 *"], { abi: ffi.FFI_WIN64 }]
});
```

After _googling_ around, It is my understanding (correct me if wrong) that `cdecl, stdcall, fastcall, thiscall` should only be used in x86.

📖 https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170
📖 https://en.wikipedia.org/wiki/X86_calling_conventions#x86-64_calling_conventions

Does using koffi.stdcall (_example_) in x64 resolve to Microsoft x64 calling convention ?

**Comment by Koromix** [comment]
Hi,

You're right, these conventions are only relevant on x86 platforms. Other platforms only provide one convention, except maybe the vectorcall convention on Windows x64 (which is not supported in Koffi at the moment).

On non-x86 platforms, Koffi ignores the specified calling convention. Which means that, if you get the convention wrong (especially if callbacks are involved), your code will work everywhere except on Node x86 where it may fail. So you may want to test it with Node 32-bit to make sure.

To be fair, for simple functions calls, because of the way Koffi is implemented, cdecl and stdcall do the same thing (and fastcall/thiscall is rarely needed). So even if you get it wrong, it will probably work. However, you have to get it right for callbacks.

This is documented here: https://koffi.dev/functions#synchronous-calls

**Comment by xan105** [comment]
Thanks I just wanted to be sure.
