### ISSUE TITLE
Use submodules?

### ISSUE THREAD

**Issue by Kreijstal** [Koromix/luigi#17]
I see in koffi/vendor you have entire repos, would it not make better sense to create git submodules on those repos instead?

**Comment by Koromix** [comment]
Hi!

Good question, and I realize it might seem weird for some people.

I vendorize dependencies on purpose, and for at least three reasons:

- I want my repository to be self-contained, so a simple git clone is guaranteed to work now and later. It won't break if the repository of a dependency moves or changes. The test and QEMU scripts depend on a few NPM modules but I don't want to depend on anything outside the repository for the actual code. And it's possible that at some point, the Koffi test code will become self-contained too (I'd like it).
- I test my code with specific dependency versions. I subscribe to release notifications for each dependency, so I know when there is an update. In most cases, the update is easy, I just have to copy everything from the release ZIP to this repository. Each dependency update is also a good time to skim through the changelog, the diff and the code.
- I can patch them easily, because they are almost as much a part of my project as my own code. I keep patch files in `vendor/_patches` and reapply them when I update a patched dependency.

Finally, I think dependencies are best avoided if possible. I take on a dependency when it adds a lot of value that I could not replicate otherwise. Dependencies have a cost, in that you lose some control over what your code is doing.

Hopefully that clears it up :)

**Comment by Koromix** [comment]
Also, the `vendor/libcc` dependency is my own, and comes from here: https://github.com/Koromix/rygel :)
