### ISSUE TITLE
koffi: prebuild binaries [Suggestion]

### ISSUE THREAD

**Issue by xan105** [Koromix/luigi#3]
I've noticed that nowadays most _native-addon_ module use _prebuild_ binary(_ies_) for convenience for the end user 
(including node-ffi-napi 😉).
Not that is complicated to compile your module, it's rather trivial actually, but you shouldn't underestimate how ease of use could boost your module popularity.

If you aren't familiar with this, the base idea is rather simple, this is something I've experienced by myself with [xan105/node-gyp-load](https://github.com/xan105/node-gyp-load) :
You basically use a npm install script in your _package.json_ to intercept and modify the install procedure.
From there you can
- check for _prebuild_ availability for the user's platform and skip the compile phase
- fetch the _prebuild_ from a remote
- check for argument to force the compilation anyway
etc...

Popular module for this are:
- [@mapbox/node-pre-gyp](https://www.npmjs.com/package/@mapbox/node-pre-gyp)
- [node-gyp-build](https://www.npmjs.com/package/node-gyp-build)

**Feel free to dismiss this as you see fit**, this is just a suggestion for convenience, something perhaps to consider for your 1.0 release when you have ironed out and complete the API / documented your project.
NB: I think it should be possible to even automate the building for the various platform with GitHub actions.

**Comment by Koromix** [comment]
Done! :) Thanks for the idea!

For version 0.9.38, which is now on NPM, prebuilt binaries should get used when installing for supported platforms/architectures (except macOS at the moment).

I use my own CMake-based tool to build Koffi ([CNoke](https://www.npmjs.com/package/cnoke)), with the goal to minimize dependencies as much as possible. I've added the necessary code to CNoke to fetch prebuilt binaries when used with `--prebuild`.

Since I already have an army of QEMU-based machines to run tests on all architectures without leaving my machine, I'm also using them to make package the builds. No cloud necessary, the way I like it :)

Well, there's still the problem of the Mac M1... Which is not supported by qemu, and for which I have no machine.

**Comment by Koromix** [comment]
FInally, if you have any other ideas to make this module more modular... I take them all ;)
